[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
fix = false

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501"]  # black handles line length

norecursedirs = [
  "pytest_*",
  ".pytest_*",
  "*/pytest_*",
  "toolrunner/pytest_tmppytest_basetemp",
]
